[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".fonts"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.0/Hack.zip"
    checksum.sha356 = "1fd74197a196dcd70bc37c811c3a629acf7554c1fb45b4b48c634a7c75953e41"
    exact = true

[".tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/refs/tags/v3.1.0.tar.gz"
    exact = true
    stripComponents = 1

[".local/bin/nvim"]
    type = "file"
    url = "https://github.com/neovim/neovim/releases/download/v0.10.4/nvim-linux-x86_64.appimage"
    checksum.sha256 = "d1b1488ef6a970dc3a2826b788d31d81b2f308ad42ef70ed62d35d0bf6189336"
    executable = true

[".local/bin/leocad"]
    type = "file"
    url = "https://github.com/leozide/leocad/releases/download/v23.03/LeoCAD-Linux-23.03-x86_64.AppImage"
    checksum.sha256 = "23c94a500f87e6b46fef366534ed822a748dec861af0150759073491eba4c0f3"
    executable = true
