[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".fonts"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Hack.zip"
    exact = true

[".tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/refs/tags/v3.1.0.tar.gz"
    exact = true
    stripComponents = 1

[".local/bin/nvim"]
    type = "file"
    url = "https://github.com/neovim/neovim/releases/download/v0.9.4/nvim.appimage"
    checksum.sha256 = "028cfaaf551d64cbb2f39d15363ed78edb01e2673579b48cb694e3604207d656"
    executable = true
