[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".local/share/fonts"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Hack.zip"
    exact = true
